import { Navbar } from './components';
import type { Metadata } from 'next';
import './styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <main className="main">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
